#!/bin/bash

echo "=========================================="
echo "OCPP Device Configuration Guide"
echo "=========================================="
echo ""

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Device information from mobile app
DEVICE_VIRTUAL_ID="bfe72084fec9521707y1c"
DEVICE_MAC="bc:35:1e:fe:1e:1f"
DEVICE_PUBLIC_IP="154.161.191.75"
WIFI_NETWORK="Les Ann Media"

# Get local network IP
LOCAL_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | head -1)

echo -e "${BLUE}Device Information (from Mobile App)${NC}"
echo "----------------------------------------"
echo "  Device Name: AFD-DY 2"
echo "  Virtual ID: $DEVICE_VIRTUAL_ID"
echo "  MAC Address: $DEVICE_MAC"
echo "  Public IP: $DEVICE_PUBLIC_IP"
echo "  WiFi Network: $WIFI_NETWORK"
echo "  Signal Strength: -42dBm (Excellent)"
echo ""

echo -e "${BLUE}Your Local Network${NC}"
echo "----------------------------------------"
echo "  Your Computer IP: $LOCAL_IP"
echo "  OCPP Gateway: ws://$LOCAL_IP:9000"
echo ""

echo -e "${YELLOW}⚠️  IMPORTANT: IP Address Issue${NC}"
echo "----------------------------------------"
echo "The mobile app shows Public IP: $DEVICE_PUBLIC_IP"
echo "This means the device might be:"
echo "  1. Using 4G/mobile data (not WiFi)"
echo "  2. Behind a router with NAT"
echo "  3. On a different network segment"
echo ""

echo -e "${BLUE}Configuration Steps${NC}"
echo "=========================================="
echo ""
echo "Step 1: Find Device's Local IP"
echo "-------------------------------"
echo "The device needs a LOCAL IP (192.168.x.x) to connect."
echo ""
echo "Methods to find local IP:"
echo "  1. Check mobile app for 'Local IP' or 'LAN IP' field"
echo "  2. Check router's DHCP client list"
echo "     - Access router: http://192.168.8.1 or http://192.168.1.1"
echo "     - Look for MAC: $DEVICE_MAC"
echo "  3. Check router admin panel → Connected Devices"
echo ""

echo "Step 2: Verify Network Connection"
echo "----------------------------------"
echo "Ensure device is connected to:"
echo "  ✅ WiFi: $WIFI_NETWORK"
echo "  ❌ NOT using 4G/mobile data"
echo ""
echo "In mobile app:"
echo "  - Go to 'Device Network'"
echo "  - Verify WiFi connection"
echo "  - Check for 'Local IP' field"
echo ""

echo "Step 3: Configure OCPP Connection"
echo "----------------------------------"
echo ""
echo -e "${GREEN}OCPP Configuration Details:${NC}"
echo ""
echo "  Charge Point ID: $DEVICE_VIRTUAL_ID"
echo "  Central System URL: ws://$LOCAL_IP:9000"
echo "  Protocol: OCPP 1.6J"
echo ""
echo "Where to configure:"
echo "  1. Mobile App → Device Settings → OCPP Settings"
echo "  2. Device Display Menu → Network → OCPP"
echo "  3. Web Interface (if accessible)"
echo ""

echo "Step 4: If Device Uses 4G/Mobile Data"
echo "--------------------------------------"
echo "If device is using 4G (public IP), you need:"
echo ""
echo "  1. Port Forwarding Setup:"
echo "     - Router: Forward external port 9000"
echo "     - To: $LOCAL_IP:9000"
echo "     - Protocol: TCP"
echo ""
echo "  2. Find Your Public IP:"
echo "     curl ifconfig.me"
echo ""
echo "  3. Configure Device:"
echo "     OCPP URL: ws://YOUR_PUBLIC_IP:9000"
echo ""

echo "Step 5: Monitor Connection"
echo "--------------------------"
echo "After configuration, monitor for connection:"
echo ""
echo "  # Watch OCPP Gateway logs"
echo "  docker logs -f ev-billing-ocpp-gateway"
echo ""
echo "  # Check for device registration"
echo "  # Login to: http://localhost:8080"
echo "  # Go to: Super Admin → Device Inventory"
echo ""

echo "=========================================="
echo "Quick Reference"
echo "=========================================="
echo ""
echo "Device Details:"
echo "  Virtual ID: $DEVICE_VIRTUAL_ID"
echo "  MAC: $DEVICE_MAC"
echo ""
echo "OCPP Gateway:"
echo "  URL: ws://$LOCAL_IP:9000"
echo "  Status: Check with: docker ps | grep ocpp-gateway"
echo ""
echo "System Access:"
echo "  Web: http://localhost:8080"
echo "  API: http://localhost:3000/api"
echo ""

