#!/bin/bash

echo "=========================================="
echo "Device Configuration Verification"
echo "=========================================="
echo ""
echo "Please verify your device configuration:"
echo ""
echo "1. Access device: http://192.168.9.106"
echo ""
echo "2. Check 'Server URL' or 'OCPP URL' field:"
echo "   Should be EXACTLY:"
echo "   ws://192.168.9.107:9000/ocpp/0900330710111935"
echo ""
echo "3. Check 'Charge Point ID' or 'Charge ID' field:"
echo "   Should be EXACTLY:"
echo "   0900330710111935"
echo ""
echo "4. Verify:"
echo "   ✅ Starts with 'ws://' (not http://)"
echo "   ✅ Includes full IP: 192.168.9.107"
echo "   ✅ Includes port: :9000"
echo "   ✅ Includes path: /ocpp/"
echo "   ✅ Includes Charge Point ID at end"
echo "   ✅ NO trailing slash after ID"
echo "   ✅ NO extra spaces"
echo ""
echo "5. After verification:"
echo "   - Save configuration"
echo "   - Reboot device"
echo "   - Wait 5 minutes"
echo "   - Monitor logs: docker logs -f ev-billing-ocpp-gateway"
echo ""
